import type { Metadata } from "next";
import { Bellefair } from "next/font/google";
import "./globals.css";

const bellefair = Bellefair({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Space Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bellefair.className} h-screen overflow-y-hidden bg-primary text-white`}
      >
        {children}
      </body>
    </html>
  );
}
